import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";

const notoSans = Noto_Sans({ variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					notoSans.variable,
					"dark flex h-dvh justify-center antialiased",
				)}
			>
				<main className="min-h-full flex-1 py-20 lg:max-w-2/3 xl:max-w-[60%]">
					{children}
				</main>
			</body>
		</html>
	);
}
